input {
  s3 {
    bucket       => "bucket_name"
    prefix       => "audit_logs"
    region       => "region"
    interval     => 60
    codec        => "cloudtrail"
    sincedb_path => "path"
    add_field    => { "[@metadata][log_type]" => "cloudtrail" }
  }
}

filter {
  if [@metadata][log_type] == "cloudtrail" {
    # Pull key fields up
    mutate {
      add_field => {
        "ct_event_name"   => "%{[eventName]}"
        "ct_event_source" => "%{[eventSource]}"
        "ct_source_ip"    => "%{[sourceIPAddress]}"
        "ct_region"       => "%{[awsRegion]}"
        "ct_user_type"    => "%{[userIdentity][type]}"
      }
    }

    mutate {
      remove_field => [ "requestParameters", "responseElements",
                        "additionalEventData", "apiVersion", "ct" ]
    }

    # Tag high-risk IAM events
    if [eventName] in ["AttachUserPolicy","PutUserPolicy","CreateAccessKey",
                       "AddUserToGroup","CreateLoginProfile","AttachRolePolicy",
                       "PutRolePolicy","UpdateAssumeRolePolicy"] {
      mutate { add_tag => ["iam_privesc_candidate"] }
    }
    if [errorCode] { mutate { add_tag => ["api_error"] } }
  }
}

output {
  if [@metadata][log_type] == "cloudtrail" {
    elasticsearch {
      hosts       => ["host"]
      index       => "cloudtrail-%{+YYYY.MM.dd}"
      user        => "user"
      password    => "pass"
      ssl_enabled => true
      ssl_certificate_authorities => ["certificate"]
    }
  }
}
