input {
  s3 {
    bucket       => "bucket_name"
    prefix       => "prefix"
    region       => "region"
    interval     => 60
    sincedb_path => "path"
    add_field    => { "[@metadata][log_type]" => "waf" }
  }
}

filter {
  if [@metadata][log_type] == "waf" {
    json { source => "message" }
    mutate {
      add_field => {
        "client_ip"  => "%{[httpRequest][clientIp]}"
        "uri"        => "%{[httpRequest][uri]}"
        "country"    => "%{[httpRequest][country]}"
        "rule_id"    => "%{[terminatingRuleId]}"
        "waf_action" => "%{[action]}"
      }
    }
    if [action] == "BLOCK" { mutate { add_tag => ["waf_block"] } }
  }
}

output {
  if [@metadata][log_type] == "waf" {
    elasticsearch {
      hosts       => ["host"]
      index       => "waf-logs-%{+YYYY.MM.dd}"
      user        => "user"
      password    => "pass"
      ssl_enabled => true
      ssl_certificate_authorities => ["cert"]
    }
  }
}
